services:
  elec_room_info:
    build:
      context: .
    image: elec_room_info:latest
    container_name: elec_room_info
    volumes:
      - ./data:/app/data # 默认 data 目录位于同目录下
    restart: on-failure:3